"""
create_mcp — 创建 MCP Server 骨架

Layer 1 元工具。生成 FastMCP 格式的 MCP Server 项目骨架。
"""

import json
from pathlib import Path

from ..base import Tool, ToolResult


_PYPROJECT_TEMPLATE = """\
[tool.poetry]
name = "{name}"
version = "0.1.0"
description = "{description}"
authors = ["Jarvis <jarvis@polly.wang>"]
packages = [{{include = "src"}}]

[tool.poetry.scripts]
{name} = "src.server:main"

[tool.poetry.dependencies]
python = "^3.11"
mcp = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
"""


_SERVER_TEMPLATE = '''\
"""
{display_name} — MCP Server

Auto-generated by Jarvis.
"""

from mcp.server.fastmcp import FastMCP

mcp = FastMCP("{display_name}")

{tools_code}

def main():
    """启动 MCP Server"""
    mcp.run(transport="stdio")


if __name__ == "__main__":
    main()
'''


_TOOL_FUNC_TEMPLATE = '''\
@mcp.tool()
def {func_name}({params_str}) -> str:
    """{description}"""
    # TODO: 实现工具逻辑
    return f"{func_name} called with: {params_log}"

'''


class CreateMCPTool(Tool):

    @property
    def name(self) -> str:
        return "create_mcp"

    @property
    def description(self) -> str:
        return (
            "创建一个 MCP Server 项目骨架。"
            "生成 pyproject.toml + server.py（FastMCP 格式），"
            "保存到 ~/.jarvis/mcp-servers/{name}/。"
        )

    @property
    def parameters(self) -> dict:
        return {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "MCP Server 名称（英文、小写、连字符，如 weather-server）",
                },
                "description": {
                    "type": "string",
                    "description": "MCP Server 描述",
                },
                "tools": {
                    "type": "array",
                    "description": "MCP 工具列表",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {"type": "string", "description": "工具函数名（snake_case）"},
                            "description": {"type": "string", "description": "工具描述"},
                            "parameters": {
                                "type": "array",
                                "description": "参数列表",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "name": {"type": "string"},
                                        "type": {"type": "string"},
                                        "description": {"type": "string"},
                                    },
                                    "required": ["name", "type"],
                                },
                            },
                        },
                        "required": ["name", "description"],
                    },
                },
            },
            "required": ["name", "description"],
        }

    async def execute(self, **kwargs) -> ToolResult:
        server_name = kwargs.get("name", "")
        description = kwargs.get("description", "")
        tools = kwargs.get("tools", [])

        if not server_name or not description:
            return ToolResult(success=False, output="", error="name 和 description 不能为空")

        # 目录
        mcp_dir = Path.home() / ".jarvis" / "mcp-servers" / server_name
        src_dir = mcp_dir / "src"
        src_dir.mkdir(parents=True, exist_ok=True)

        display_name = server_name.replace("-", " ").title()
        created_files = []

        # pyproject.toml
        pyproject = _PYPROJECT_TEMPLATE.format(name=server_name, description=description)
        pyproject_path = mcp_dir / "pyproject.toml"
        pyproject_path.write_text(pyproject, encoding="utf-8")
        created_files.append(str(pyproject_path))

        # src/__init__.py
        init_path = src_dir / "__init__.py"
        init_path.write_text(f'"""{display_name}"""\n', encoding="utf-8")
        created_files.append(str(init_path))

        # 生成工具函数代码
        tools_code_parts = []
        for tool_def in tools:
            func_name = tool_def.get("name", "my_tool")
            tool_desc = tool_def.get("description", "TODO")
            params = tool_def.get("parameters", [])

            # 构建参数字符串
            param_parts = []
            log_parts = []
            for p in params:
                p_name = p.get("name", "arg")
                p_type = p.get("type", "str")
                p_desc = p.get("description", "")
                param_parts.append(f'{p_name}: {p_type}')
                log_parts.append(f'{p_name}={{{p_name}}}')

            params_str = ", ".join(param_parts) if param_parts else ""
            params_log = ", ".join(log_parts) if log_parts else "no args"

            tools_code_parts.append(
                _TOOL_FUNC_TEMPLATE.format(
                    func_name=func_name,
                    params_str=params_str,
                    description=tool_desc,
                    params_log=params_log,
                )
            )

        tools_code = "\n".join(tools_code_parts) if tools_code_parts else "# TODO: Add tools\npass\n"

        # server.py
        server_code = _SERVER_TEMPLATE.format(
            display_name=display_name,
            tools_code=tools_code,
        )
        server_path = src_dir / "server.py"
        server_path.write_text(server_code, encoding="utf-8")
        created_files.append(str(server_path))

        files_list = "\n".join(f"  📄 {f}" for f in created_files)
        return ToolResult(
            success=True,
            output=(
                f"✅ MCP Server '{server_name}' 已创建:\n{files_list}\n\n"
                f"📦 安装: cd {mcp_dir} && poetry install\n"
                f"🚀 运行: poetry run {server_name}"
            ),
            metadata={"server_name": server_name, "path": str(mcp_dir), "files": created_files},
        )
